// Code generated by protoc-gen-go. DO NOT EDIT.
// source: example/greeter/greeter.proto

package greeter // import "github.com/lukasjarosch/microservice-structure-protobuf/example/greeter"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GreetingRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingRequest) Reset()         { *m = GreetingRequest{} }
func (m *GreetingRequest) String() string { return proto.CompactTextString(m) }
func (*GreetingRequest) ProtoMessage()    {}
func (*GreetingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_884eadd021b3c4fa, []int{0}
}
func (m *GreetingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingRequest.Unmarshal(m, b)
}
func (m *GreetingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingRequest.Marshal(b, m, deterministic)
}
func (dst *GreetingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingRequest.Merge(dst, src)
}
func (m *GreetingRequest) XXX_Size() int {
	return xxx_messageInfo_GreetingRequest.Size(m)
}
func (m *GreetingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingRequest proto.InternalMessageInfo

func (m *GreetingRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GreetingResponse struct {
	Greeting             string   `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GreetingResponse) Reset()         { *m = GreetingResponse{} }
func (m *GreetingResponse) String() string { return proto.CompactTextString(m) }
func (*GreetingResponse) ProtoMessage()    {}
func (*GreetingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_884eadd021b3c4fa, []int{1}
}
func (m *GreetingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GreetingResponse.Unmarshal(m, b)
}
func (m *GreetingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GreetingResponse.Marshal(b, m, deterministic)
}
func (dst *GreetingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GreetingResponse.Merge(dst, src)
}
func (m *GreetingResponse) XXX_Size() int {
	return xxx_messageInfo_GreetingResponse.Size(m)
}
func (m *GreetingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GreetingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GreetingResponse proto.InternalMessageInfo

func (m *GreetingResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

type FarewellRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FarewellRequest) Reset()         { *m = FarewellRequest{} }
func (m *FarewellRequest) String() string { return proto.CompactTextString(m) }
func (*FarewellRequest) ProtoMessage()    {}
func (*FarewellRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_884eadd021b3c4fa, []int{2}
}
func (m *FarewellRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FarewellRequest.Unmarshal(m, b)
}
func (m *FarewellRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FarewellRequest.Marshal(b, m, deterministic)
}
func (dst *FarewellRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FarewellRequest.Merge(dst, src)
}
func (m *FarewellRequest) XXX_Size() int {
	return xxx_messageInfo_FarewellRequest.Size(m)
}
func (m *FarewellRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FarewellRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FarewellRequest proto.InternalMessageInfo

func (m *FarewellRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type FarewellResponse struct {
	Farewell             string   `protobuf:"bytes,1,opt,name=farewell,proto3" json:"farewell,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FarewellResponse) Reset()         { *m = FarewellResponse{} }
func (m *FarewellResponse) String() string { return proto.CompactTextString(m) }
func (*FarewellResponse) ProtoMessage()    {}
func (*FarewellResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_greeter_884eadd021b3c4fa, []int{3}
}
func (m *FarewellResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FarewellResponse.Unmarshal(m, b)
}
func (m *FarewellResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FarewellResponse.Marshal(b, m, deterministic)
}
func (dst *FarewellResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FarewellResponse.Merge(dst, src)
}
func (m *FarewellResponse) XXX_Size() int {
	return xxx_messageInfo_FarewellResponse.Size(m)
}
func (m *FarewellResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FarewellResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FarewellResponse proto.InternalMessageInfo

func (m *FarewellResponse) GetFarewell() string {
	if m != nil {
		return m.Farewell
	}
	return ""
}

func init() {
	proto.RegisterType((*GreetingRequest)(nil), "example.greeter.GreetingRequest")
	proto.RegisterType((*GreetingResponse)(nil), "example.greeter.GreetingResponse")
	proto.RegisterType((*FarewellRequest)(nil), "example.greeter.FarewellRequest")
	proto.RegisterType((*FarewellResponse)(nil), "example.greeter.FarewellResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// HelloClient is the client API for Hello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type HelloClient interface {
	Greeting(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error)
	Farewell(ctx context.Context, in *FarewellRequest, opts ...grpc.CallOption) (*FarewellResponse, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) Greeting(ctx context.Context, in *GreetingRequest, opts ...grpc.CallOption) (*GreetingResponse, error) {
	out := new(GreetingResponse)
	err := c.cc.Invoke(ctx, "/example.greeter.Hello/Greeting", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) Farewell(ctx context.Context, in *FarewellRequest, opts ...grpc.CallOption) (*FarewellResponse, error) {
	out := new(FarewellResponse)
	err := c.cc.Invoke(ctx, "/example.greeter.Hello/Farewell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HelloServer is the server API for Hello service.
type HelloServer interface {
	Greeting(context.Context, *GreetingRequest) (*GreetingResponse, error)
	Farewell(context.Context, *FarewellRequest) (*FarewellResponse, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_Greeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GreetingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Greeting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.greeter.Hello/Greeting",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Greeting(ctx, req.(*GreetingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_Farewell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FarewellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Farewell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.greeter.Hello/Farewell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Farewell(ctx, req.(*FarewellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.greeter.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greeting",
			Handler:    _Hello_Greeting_Handler,
		},
		{
			MethodName: "Farewell",
			Handler:    _Hello_Farewell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "example/greeter/greeter.proto",
}

func init() {
	proto.RegisterFile("example/greeter/greeter.proto", fileDescriptor_greeter_884eadd021b3c4fa)
}

var fileDescriptor_greeter_884eadd021b3c4fa = []byte{
	// 311 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0x4f, 0x4b, 0xf3, 0x40,
	0x10, 0xc6, 0xc9, 0xcb, 0xab, 0xd4, 0x45, 0xa8, 0xe6, 0xa2, 0x04, 0x85, 0x1a, 0x10, 0xa4, 0x98,
	0x5d, 0xd4, 0x5b, 0x8f, 0x1e, 0xac, 0x5e, 0x7b, 0xf4, 0xb6, 0x5d, 0xa6, 0xdb, 0xd5, 0xcd, 0x4e,
	0xdc, 0x3f, 0xad, 0x67, 0xbf, 0x82, 0x1f, 0xcd, 0xa3, 0x57, 0x3f, 0x88, 0x34, 0xcd, 0x1a, 0x8c,
	0x45, 0x4f, 0x93, 0x99, 0xf9, 0xf1, 0x3c, 0xf3, 0x24, 0x21, 0xc7, 0xf0, 0xcc, 0xcb, 0x4a, 0x03,
	0x93, 0x16, 0xc0, 0x83, 0x8d, 0x95, 0x56, 0x16, 0x3d, 0xa6, 0xfd, 0x66, 0x4d, 0x9b, 0x71, 0x76,
	0x24, 0x11, 0xa5, 0x06, 0xc6, 0x2b, 0xc5, 0xb8, 0x31, 0xe8, 0xb9, 0x57, 0x68, 0xdc, 0x1a, 0xcf,
	0xce, 0xeb, 0x22, 0x0a, 0x09, 0xa6, 0x70, 0x4b, 0x2e, 0x25, 0x58, 0x86, 0x55, 0x4d, 0xfc, 0xa4,
	0xf3, 0x53, 0xd2, 0x1f, 0xaf, 0x64, 0x95, 0x91, 0x13, 0x78, 0x0a, 0xe0, 0x7c, 0x9a, 0x92, 0xff,
	0x86, 0x97, 0x70, 0x98, 0x0c, 0x92, 0xb3, 0x9d, 0x49, 0xfd, 0x9c, 0x53, 0xb2, 0xd7, 0x62, 0xae,
	0x42, 0xe3, 0x20, 0xcd, 0x48, 0x4f, 0x36, 0xb3, 0x86, 0xfd, 0xea, 0x57, 0xb2, 0x37, 0xdc, 0xc2,
	0x12, 0xb4, 0xfe, 0x43, 0xb6, 0xc5, 0x5a, 0xd9, 0x59, 0x33, 0x8b, 0xb2, 0xb1, 0xbf, 0x7c, 0x4f,
	0xc8, 0xd6, 0x2d, 0x68, 0x8d, 0xe9, 0x9c, 0xf4, 0xe2, 0x41, 0xe9, 0x80, 0x76, 0xde, 0x10, 0xed,
	0x44, 0xca, 0x4e, 0x7e, 0x21, 0xd6, 0xb6, 0xf9, 0xc1, 0xcb, 0xdb, 0xc7, 0xeb, 0xbf, 0xfd, 0x7c,
	0x97, 0x2d, 0x2e, 0x58, 0xcc, 0x31, 0x4a, 0x86, 0x2b, 0xa7, 0x78, 0xe3, 0x06, 0xa7, 0x4e, 0xca,
	0x0d, 0x4e, 0xdd, 0x80, 0xdf, 0x9d, 0x62, 0xb4, 0x51, 0x32, 0xbc, 0xbe, 0xbb, 0x1f, 0x4b, 0xe5,
	0xe7, 0x61, 0x4a, 0x05, 0x96, 0x4c, 0x87, 0x47, 0xee, 0x1e, 0xb8, 0x45, 0x27, 0xe6, 0xac, 0x54,
	0xc2, 0xa2, 0x03, 0xbb, 0x50, 0x02, 0x0a, 0xe7, 0x6d, 0x10, 0x3e, 0x58, 0x28, 0xea, 0x6f, 0x38,
	0x0d, 0x33, 0xd6, 0xf9, 0x83, 0xa6, 0xdb, 0xf5, 0xe6, 0xea, 0x33, 0x00, 0x00, 0xff, 0xff, 0x9f,
	0xb4, 0x4c, 0xf4, 0x5b, 0x02, 0x00, 0x00,
}
