language: go
go:
  - 1.12.x

install:
  - GO111MODULE=on go get github.com/uber/prototool/cmd/prototool
  - go get -v -d google.golang.org/grpc
  - go get -v -d -t github.com/golang/protobuf/...

script:
  - ./scripts/build.sh
