language: go
sudo: required

go:
  - 1.12.x

services:
  - docker

install:
  - docker pull uber/prototool:latest

script:
  - mkdir -p gen/go
  - ./scripts/prototool.sh generate
  - ./scripts/push.sh
  - ls -la
  - ls -la gen
  - ls -la gen/go
