language: go

go:
  - 1.12.x

services:
  - docker

install:
  - docker pull uber/prototool:latest

script:
  - USER="$(id -u):$(id -g)"
  - docker run -v "$(pwd)":/work uber/prototool:latest prototool generate
  - ./scripts/push.sh
