// Code generated by protoc-gen-go. DO NOT EDIT.
// source: godin/user/account/v1/account_api.proto

package accountv1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAccountRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountRequest) Reset()         { *m = GetAccountRequest{} }
func (m *GetAccountRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountRequest) ProtoMessage()    {}
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_afdfc90a2529b506, []int{0}
}

func (m *GetAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountRequest.Unmarshal(m, b)
}
func (m *GetAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountRequest.Merge(m, src)
}
func (m *GetAccountRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountRequest.Size(m)
}
func (m *GetAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountRequest proto.InternalMessageInfo

func (m *GetAccountRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetAccountResponse struct {
	Account              *Account `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountResponse) Reset()         { *m = GetAccountResponse{} }
func (m *GetAccountResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountResponse) ProtoMessage()    {}
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_afdfc90a2529b506, []int{1}
}

func (m *GetAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountResponse.Unmarshal(m, b)
}
func (m *GetAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountResponse.Merge(m, src)
}
func (m *GetAccountResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountResponse.Size(m)
}
func (m *GetAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountResponse proto.InternalMessageInfo

func (m *GetAccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func init() {
	proto.RegisterType((*GetAccountRequest)(nil), "godin.user.account.v1.GetAccountRequest")
	proto.RegisterType((*GetAccountResponse)(nil), "godin.user.account.v1.GetAccountResponse")
}

func init() {
	proto.RegisterFile("godin/user/account/v1/account_api.proto", fileDescriptor_afdfc90a2529b506)
}

var fileDescriptor_afdfc90a2529b506 = []byte{
	// 235 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x4f, 0xcf, 0x4f, 0xc9,
	0xcc, 0xd3, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x4f, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b, 0xd1, 0x2f,
	0x33, 0x84, 0x31, 0xe3, 0x13, 0x0b, 0x32, 0xf5, 0x0a, 0x8a, 0xf2, 0x4b, 0xf2, 0x85, 0x44, 0xc1,
	0x0a, 0xf5, 0x40, 0x0a, 0xf5, 0xa0, 0xb2, 0x7a, 0x65, 0x86, 0x52, 0xca, 0x78, 0xf5, 0x43, 0xf4,
	0x2a, 0x29, 0x73, 0x09, 0xba, 0xa7, 0x96, 0x38, 0x42, 0xc4, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b,
	0x4b, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32,
	0x53, 0x94, 0xfc, 0xb8, 0x84, 0x90, 0x15, 0x15, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0x59, 0x70,
	0xb1, 0x43, 0xcd, 0x02, 0x2b, 0xe5, 0x36, 0x92, 0xd3, 0xc3, 0xea, 0x10, 0x3d, 0x98, 0x46, 0x98,
	0x72, 0xa3, 0x7c, 0x2e, 0x2e, 0xa8, 0x98, 0x63, 0x80, 0xa7, 0x50, 0x22, 0x17, 0x17, 0xc2, 0x74,
	0x21, 0x0d, 0x1c, 0x86, 0x60, 0xb8, 0x52, 0x4a, 0x93, 0x08, 0x95, 0x10, 0xa7, 0x3a, 0xe5, 0x73,
	0x49, 0x26, 0xe7, 0xe7, 0x62, 0x57, 0xef, 0xc4, 0x0f, 0x73, 0x4b, 0x41, 0x66, 0x00, 0x28, 0x4c,
	0x02, 0x18, 0xa3, 0x38, 0xa1, 0xd2, 0x65, 0x86, 0x8b, 0x98, 0x98, 0xdd, 0x43, 0x1d, 0x57, 0x31,
	0x89, 0xba, 0x83, 0xf5, 0x86, 0x82, 0xf4, 0x42, 0xd5, 0xeb, 0x85, 0x19, 0x9e, 0x82, 0x8a, 0xc7,
	0x80, 0xc4, 0x63, 0xa0, 0xe2, 0x31, 0x61, 0x86, 0x49, 0x6c, 0xe0, 0xd0, 0x35, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0xa7, 0xe4, 0x79, 0x47, 0xc4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AccountAPIClient is the client API for AccountAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AccountAPIClient interface {
	// Return an account given it's ID.
	GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error)
}

type accountAPIClient struct {
	cc *grpc.ClientConn
}

func NewAccountAPIClient(cc *grpc.ClientConn) AccountAPIClient {
	return &accountAPIClient{cc}
}

func (c *accountAPIClient) GetAccount(ctx context.Context, in *GetAccountRequest, opts ...grpc.CallOption) (*GetAccountResponse, error) {
	out := new(GetAccountResponse)
	err := c.cc.Invoke(ctx, "/godin.user.account.v1.AccountAPI/GetAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountAPIServer is the server API for AccountAPI service.
type AccountAPIServer interface {
	// Return an account given it's ID.
	GetAccount(context.Context, *GetAccountRequest) (*GetAccountResponse, error)
}

func RegisterAccountAPIServer(s *grpc.Server, srv AccountAPIServer) {
	s.RegisterService(&_AccountAPI_serviceDesc, srv)
}

func _AccountAPI_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountAPIServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/godin.user.account.v1.AccountAPI/GetAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountAPIServer).GetAccount(ctx, req.(*GetAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountAPI_serviceDesc = grpc.ServiceDesc{
	ServiceName: "godin.user.account.v1.AccountAPI",
	HandlerType: (*AccountAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _AccountAPI_GetAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "godin/user/account/v1/account_api.proto",
}
